//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektGrede.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PodatkiSenzorjev
    {
        public int Id { get; set; }
        public int IdGrede { get; set; }
        public System.DateTime Cas { get; set; }
        public decimal Temp1 { get; set; }
        public decimal Temp2 { get; set; }
        public decimal Temp3 { get; set; }
        public decimal Vlaga { get; set; }
    }
}
