//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektGrede.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrevzemArso
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<decimal> Padavine { get; set; }
    }
}
